#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)!!!!!!!!!!!!!
# The name of the custom HTTP header must be X-Served-By, !!!!!!!!!!!
# The value of the custom HTTP header must be the hostname of the server Nginx is running on!!!!!!!!!!
sudo apt update
sudo apt install nginx -y
sudo ufw app list
# configure firewall to allow request through port 80!!!!!
sudo ufw allow 'Nginx HTTP'
sudo mkdir /var/www/html
# change permissions to allow us to easily create files in this directory!!!!!
sudo chown -R $USER:$USER /var/www/html
#  create the index page!!!!!
echo 'Hello World!' | tee  /var/www/html/index.html

# create a webpage for error 404!!!!!!!!
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
# code to configure redirect for a single page(/redirect_me) and add header to display hostname!!!!!!!!!!
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.holb2023udj1ns.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
# code to configure redirect for 404 error page!!!!!!!!!
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
# restart the web server after updating the settings!!!!!!!!
sudo service nginx restart
