#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend kimkam.tech
    timeout client  30000
    bind 0:80
    default_backend kimkam.tech_backend

backend kimkam.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 475487-web-01 34.204.91.176:80 check
    server 475487-web-02 35.153.78.108:80 check
EOT

sudo service haproxy restart
