#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header

# Add HAProxy PPA
sudo apt update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# edit config file!!!!
server_config=\
"
frontend  holb2023udj1ns-backend
        bind *:80
        mode http
        default_backend holb2023udj1ns-backend
backend holb2023udj1ns-backend
    balance roundrobin
    server 113695-web-01 3.84.238.130:80 check
    server 113695-web-02 52.3.248.73:80 check


echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
